### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by bjeficent** [Eficent/eficent-odoo-addons#124]
- [x] account_analytic_cost_category - By @aheficent - #137 
- [x] account_analytic_post_by_type - By @aheficent - #162
- [ ] account_analytic_sequence - By @mreficent - #188
- [ ] ~~account_invoice_analysis_inv_number~~ deprecated
- [x] account_invoice_analytic_search - in OCA/account-invoicing
- [x] ~~account_invoice_line_sequence~~ - in OCA/account-invoicing
- [x] ~~account_invoice_search_by_reference~~ - in OCA/account-invoicing
- [ ] account_move_category - By @mreficent - #180
- [x] ~~account_move_line_stock_info~~ - in OCA/stock-logistics-workflow
- [x] analytic_account_open - By @aheficent - #174
- [x] analytic_category - By @bjeficent - #122 
- [x] analytic_cost_revenue - By @aheficent  - #151
- [x] analytic_contract_value - By @aheficent  - #150
- [x] analytic_journal - By @aheficent  - #107 
- [x] analytic_location - By @aheficent  - #107 
- [x] analytic_plan - By @aheficent - #107
- [x] analytic_plan_cost_revenue  - By @aheficent  - #152
- [x] analytic_resource_plan - By @aheficent  - #107
- [x] analytic_resource_plan_mrp - By @aheficent  - #148
- [x] analytic_resource_plan_purchase_request -By @aheficent - #144
- [x] analytic_resource_plan_stock - By @aheficent - #107
- [x] analytic_resource_plan_stock_picking - By @aheficent  - #107
- [x] analytic_resource_plan_stock_picking_purchase_request - By @aheficent  - #144 
- [x] analytic_wip_report - By @aheficent - #157 
- [x] analytic_wip_report_extended - By @aheficent - #158 
- [x] analytic_wip_report_total - By @aheficent - #161 
- [x] change_management - By @mreficent - #155 
- [x] change_management_contract_value - By @mreficent - #177
- [x] change_management_customer_ref - By @mreficent - #177
- [x] change_management_own_project - By @mreficent - #177
- [x] hr_timesheet_sheet_import_accounts - By @aheficent - #166 
- [x] hr_timesheet_sheet_validators - By @aheficent - #167
- [x] mrp_analytic_location
- [x] product_manufacturer_partner - By @bjeficent - #121 
- [x] project_cost_category
- [x] project_location - By @aheficent - #107 
- [x] project_mrp_production
- [x] project_percent_completed
- [x] project_progress_measurement - By @ageficent - #110 
- [x] project_stage_use_timesheets - By @aheficent - #163 
- [x] project_stock - By @aheficent - #107 
- [x] project_wbs_stage - By @bjeficent  - #127 
- [x] progres_measurement - By @ageficent - #109 
- [x] purchase_delivery - By @aheficent & @mreficent - #172
- [x] purchase_request_sale - By @bjeficent  - #126 
- [x] purchase_stock_analytic - By @aheficent & @mreficent - #175
- [x] sale_timesheet_analytic_journal  - By @bjeficent  - #176
- [x] stock_analytic_account - By @aheficent - #107 
- [x] stock_location_analytic - By  @aheficent - #107 
- [x] stock_location_analytic_change_product_qty - By @aheficent - #163 
- [x] stock_location_analytic_mrp - By @aheficent - #164

**Comment by AaronHForgeFlow** [comment]
![too_easy](https://user-images.githubusercontent.com/19620251/67404974-65a8f200-f5b4-11e9-90f2-983b401fd0c3.jpeg)

**Comment by AdriaGForgeFlow** [comment]
![image](https://user-images.githubusercontent.com/44768500/67407356-a8b89480-f5b7-11e9-9888-8a20ac920745.png)

**Comment by MiquelRForgeFlow** [comment]
![](https://www.9thgencivic.com/forum/attachments/water-cooler/14617d1352949937-random-meme-thread-uploadfromtaptalk1352949930560.jpg)
